/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SearchFlights;

import Business.Flight;
import Business.FlightSchedule;
import Business.Users.Airliner;
import UserInterface.SearchAirliners.SearchAirlinersJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class SearchFlightsDisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchFlightsDisplayJPanel
     */
   private JPanel CardSequenceJPanel;
    private  FlightSchedule fs;
    public SearchFlightsDisplayJPanel(  JPanel CardSequenceJPanel,  FlightSchedule fs) {
        initComponents();
        this.fs=fs;
        this.CardSequenceJPanel=CardSequenceJPanel;
        populate();
    }
public void populate()
{
    DefaultTableModel dtm=(DefaultTableModel)airlinerjtable1.getModel();
    dtm.setRowCount(0);

     for(Flight k: fs.getFlightschedule())
        {   System.out.println(k);
            Object[]row=new Object[dtm.getColumnCount()];
            row[0]=k;
            row[1]=k.getAirplaneNum();
            row[2]=k.getDepartLoc();
            row[3]=k.getArrivalLoc();
            row[4]=k.getDeptDate();
            row[5]=k.getArrivalDate();
            dtm.addRow(row);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        airlinerjtable1 = new javax.swing.JTable();
        viewbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        airlinerjtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "FlightNumber", "AirPlaneNum", "DepartmentLocation", "ArrivalLocation", "DepartmentDate", "ArriveTime"
            }
        ));
        jScrollPane2.setViewportView(airlinerjtable1);

        viewbtn.setText("View Flights");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        jButton2.setText("<-Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewbtn)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        // TODO add your handling code here:
         int selectedRow= airlinerjtable1.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "please select a row from table first","warning",JOptionPane.WARNING_MESSAGE);

        }               
        else
        {

            
                  System.out.println("dsdasadsdasdasdasdasdasda");
                  Flight ff=(Flight) airlinerjtable1.getValueAt(selectedRow, 0);
                  ViewFlightsDetailJPanel vf=new ViewFlightsDetailJPanel(CardSequenceJPanel,ff);
                  CardSequenceJPanel.add("ViewFlightsDeatailJPanel",vf);
                  CardLayout layout= (CardLayout)CardSequenceJPanel.getLayout();
                  layout.next(CardSequenceJPanel);
                
            }
  
        
        
    }//GEN-LAST:event_viewbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout=(CardLayout) CardSequenceJPanel.getLayout();
     
        // CardLayout layout=(CardLayout) CardSequenceJPanel.getLayout();
       // layout.previous(CardSequenceJPanel);
         Component[] comps=this.CardSequenceJPanel.getComponents();
        for(Component comp: comps)
        {
            if(comp instanceof SearchAirlinersJPanel)
            {
                SearchAirlinersJPanel manageProdPanel = (SearchAirlinersJPanel) comp;
                
                manageProdPanel.populate();
            }
        }
        layout.previous(CardSequenceJPanel);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlinerjtable1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
