/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WarehousemanWorkArea;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yizhe
 */
public class WarehousemanWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehousemanWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    Enterprise enterprise;

    public WarehousemanWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StockJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        JComName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUpdateQu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(224, 224, 224));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(null);

        btnCreate.setBackground(getBackground());
        btnCreate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 0, 0));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(994, 169, 88, 40);

        btnDelete.setBackground(getBackground());
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        add(btnDelete);
        btnDelete.setBounds(987, 434, 95, 40);

        btnUpdate.setBackground(getBackground());
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        add(btnUpdate);
        btnUpdate.setBounds(990, 337, 92, 40);

        jLabel4.setBackground(getBackground());
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Pharmacy Supplier System - Warehouse - Warehouseman");
        add(jLabel4);
        jLabel4.setBounds(33, 44, 891, 32);

        backJButton.setBackground(getBackground());
        backJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 0, 0));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(990, 520, 100, 40);

        StockJTable.setBackground(new java.awt.Color(224, 224, 224));
        StockJTable.setForeground(new java.awt.Color(255, 255, 255));
        StockJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Medicine Name", "Stock Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockJTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(StockJTable);
        if (StockJTable.getColumnModel().getColumnCount() > 0) {
            StockJTable.getColumnModel().getColumn(0).setResizable(false);
            StockJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(33, 114, 622, 440);

        jLabel1.setBackground(getBackground());
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");
        add(jLabel1);
        jLabel1.setBounds(729, 114, 58, 24);

        txtMedName.setBackground(getBackground());
        txtMedName.setForeground(new java.awt.Color(0, 0, 0));
        add(txtMedName);
        txtMedName.setBounds(841, 116, 124, 24);

        jLabel2.setBackground(getBackground());
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Quantity:");
        add(jLabel2);
        jLabel2.setBounds(729, 177, 81, 24);

        txtQuantity.setBackground(getBackground());
        txtQuantity.setForeground(new java.awt.Color(0, 0, 0));
        add(txtQuantity);
        txtQuantity.setBounds(841, 177, 124, 29);

        JComName.setBackground(getBackground());
        JComName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JComName.setForeground(new java.awt.Color(0, 0, 0));
        JComName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Antibiotics", "albomycin", "berberine", "penicillin G", "Analgesics", "aspirin", "Vitamins" }));
        JComName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComNameActionPerformed(evt);
            }
        });
        add(JComName);
        JComName.setBounds(841, 274, 120, 34);

        jLabel5.setBackground(getBackground());
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name:");
        add(jLabel5);
        jLabel5.setBounds(729, 279, 58, 24);

        jLabel6.setBackground(getBackground());
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantity:");
        add(jLabel6);
        jLabel6.setBounds(721, 345, 81, 24);

        txtUpdateQu.setBackground(getBackground());
        txtUpdateQu.setForeground(new java.awt.Color(0, 0, 0));
        add(txtUpdateQu);
        txtUpdateQu.setBounds(841, 345, 120, 29);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/center - Copy.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        add(jLabel14);
        jLabel14.setBounds(0, 0, 1920, 960);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void JComNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
          String medicineName=txtMedName.getText(); //getmedicinename
             if(medicineName==null || medicineName.equals("")){
                 JOptionPane.showMessageDialog(null,"The Medicine Name cannot be empty");
                 return;
             }
       String medicineQuantity=txtQuantity.getText();  //gettext
             if(medicineQuantity==null || medicineQuantity.equals("")){
                 JOptionPane.showMessageDialog(null,"The Quantity cannot be empty");
                 return;
             }
             
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComName;
    private javax.swing.JTable StockJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUpdateQu;
    // End of variables declaration//GEN-END:variables
}
