/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarCatalog;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yizhe
 */
public class Search2ndCarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Search2ndCarJPanel
     */
    private JPanel OperateJPanel;
    private CarCatalog carcatalog;
    private CarCatalog cc;
    public Search2ndCarJPanel(JPanel OperateJPanel,CarCatalog carcatalog) {
        initComponents();
        this.OperateJPanel=OperateJPanel;
        this.carcatalog=carcatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ViewJTable = new javax.swing.JTable();
        btnAvailCar = new javax.swing.JButton();
        btnAvailCityCar = new javax.swing.JButton();
        CityTF = new javax.swing.JTextField();

        setBackground(java.awt.Color.darkGray);
        setPreferredSize(new java.awt.Dimension(810, 620));

        ViewJTable.setBackground(new java.awt.Color(0, 0, 0));
        ViewJTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ViewJTable.setForeground(new java.awt.Color(255, 255, 255));
        ViewJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City", "SerialNo", "ModelNo", "Manufacturer", "Seats", "Maintanence Certificate", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ViewJTable.setGridColor(new java.awt.Color(255, 255, 255));
        ViewJTable.setSelectionBackground(new java.awt.Color(255, 255, 0));
        ViewJTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(ViewJTable);

        btnAvailCar.setBackground(new java.awt.Color(0, 0, 0));
        btnAvailCar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAvailCar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvailCar.setText("Available Car");
        btnAvailCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailCarActionPerformed(evt);
            }
        });

        btnAvailCityCar.setBackground(new java.awt.Color(0, 0, 0));
        btnAvailCityCar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAvailCityCar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvailCityCar.setText("Given Car City");
        btnAvailCityCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailCityCarActionPerformed(evt);
            }
        });

        CityTF.setBackground(java.awt.Color.darkGray);
        CityTF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CityTF.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAvailCityCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CityTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAvailCar, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnAvailCar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(CityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAvailCityCar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvailCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailCarActionPerformed
        // TODO add your handling code here:
        cc=new CarCatalog();
        DefaultTableModel dtm=(DefaultTableModel)ViewJTable.getModel();
        dtm.setRowCount(0);
        for(Car car:carcatalog.getCarCatalog()){
            if(car.isAvailCar()==true) 
            {
                Car c=cc.addCar();
                Object row[]=new Object[6];
                row[0]=car;
                row[1]=car.getSerialNo();
                row[2]=car.getModelNo();
                row[3]=car.getManufacturer();
                row[4]=car.getSeats();
                row[5]=car.isMaintenanceCertificate();
                dtm.addRow(row);
                
                c.setAvailCar(car.isAvailCar());
                c.setManufacturer(car.getManufacturer());
                c.setManufactureYear(car.getManufactureYear());
                c.setSeats(car.getSeats() );
                c.setSerialNo(car.getSerialNo());
                c.setModelNo(car.getModelNo());
                c.setCatalogTime(car.getCatalogTime());
                c.setCity(car.getCity());
                c.setMaintenanceCertificate(car.isMaintenanceCertificate());
                
            }
        }
    }//GEN-LAST:event_btnAvailCarActionPerformed

    private void btnAvailCityCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailCityCarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)ViewJTable.getModel();
        dtm.setRowCount(0);
        for(Car car:cc.getCarCatalog()){
            if(car.getCity().equals(CityTF.getText())) 
            {
                Object row[]=new Object[6];
                row[0]=car;
                row[1]=car.getSerialNo();
                row[2]=car.getModelNo();
                row[3]=car.getManufacturer();
                row[4]=car.getSeats();
                row[5]=car.isMaintenanceCertificate();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_btnAvailCityCarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CityTF;
    private javax.swing.JTable ViewJTable;
    private javax.swing.JButton btnAvailCar;
    private javax.swing.JButton btnAvailCityCar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
