/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NetworkAdminWorkArea;

import Business.HIS;
import Business.People.People;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.HAdminRole;
import Business.Role.MIAdminRole;
import Business.Role.PSAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HIS system;
    Network network;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, Network network,HIS system) {
        initComponents();
        this.network=network;
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateNetworkComboBox();
        populateEnterpriseComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = userAccount;
                    row[1] = enterprise.getName();
                    row[2] = network.getName();
                    

                    model.addRow(row);
                }
            }
        
    }

    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        networkJComboBox.addItem(network);
        
    }
    
    private void populateEnterpriseComboBox(){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseJComboBox.addItem(enterprise);
            
        }
        
    }
     private void populateEnterpriseType(Enterprise e){
        for (Network n:system.getNetworkList()){
            for(Enterprise ep:n.getEnterpriseDirectory().getEnterpriseList()){
                if(ep==e){
                    enterpriseTypeJTF.setText(e.getEnterpriseType().toString());
                }
            }
        }
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        enterpriseTypeJTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        renameJB = new javax.swing.JButton();
        renameJTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        delJB = new javax.swing.JButton();
        delnameJTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(224, 224, 224));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        enterpriseJTable.setBackground(new java.awt.Color(224, 224, 224));
        enterpriseJTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Enterprise Name", "Network"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseJTable.setGridColor(new java.awt.Color(0, 0, 0));
        enterpriseJTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        enterpriseJTable.setSelectionForeground(new java.awt.Color(255, 255, 0));
        enterpriseJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterpriseJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);
        if (enterpriseJTable.getColumnModel().getColumnCount() > 0) {
            enterpriseJTable.getColumnModel().getColumn(0).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(1).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setBackground(new java.awt.Color(118, 138, 168));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Network");

        networkJComboBox.setBackground(new java.awt.Color(224, 224, 224));
        networkJComboBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(118, 138, 168));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Username");

        usernameJTextField.setBackground(new java.awt.Color(224, 224, 224));
        usernameJTextField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        usernameJTextField.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(118, 138, 168));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Enterprise");

        enterpriseJComboBox.setBackground(new java.awt.Color(224, 224, 224));
        enterpriseJComboBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });

        submitJButton.setBackground(new java.awt.Color(224, 224, 224));
        submitJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(118, 138, 168));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        nameJTextField.setBackground(new java.awt.Color(224, 224, 224));
        nameJTextField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameJTextField.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(118, 138, 168));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Name");

        passwordJPasswordField.setBackground(new java.awt.Color(224, 224, 224));
        passwordJPasswordField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        passwordJPasswordField.setCaretColor(new java.awt.Color(255, 255, 255));

        backJButton.setBackground(new java.awt.Color(224, 224, 224));
        backJButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(118, 138, 168));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Enterprise Type");

        enterpriseTypeJTF.setEditable(false);
        enterpriseTypeJTF.setBackground(new java.awt.Color(224, 224, 224));
        enterpriseTypeJTF.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        enterpriseTypeJTF.setCaretColor(new java.awt.Color(255, 255, 255));
        enterpriseTypeJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeJTFActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(118, 138, 168));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Hospital Information System Enterprise Admin");

        jLabel7.setBackground(new java.awt.Color(118, 138, 168));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Create New Enterprise Admin:");

        jLabel9.setBackground(new java.awt.Color(118, 138, 168));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Rename Selected Enterprise Admin Username:");

        renameJB.setBackground(new java.awt.Color(224, 224, 224));
        renameJB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        renameJB.setText("Submit");
        renameJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameJBActionPerformed(evt);
            }
        });

        renameJTF.setBackground(new java.awt.Color(224, 224, 224));
        renameJTF.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        renameJTF.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(118, 138, 168));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("ReName");

        jLabel11.setBackground(new java.awt.Color(118, 138, 168));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Username");

        delJB.setBackground(new java.awt.Color(224, 224, 224));
        delJB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        delJB.setText("Delete");
        delJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delJBActionPerformed(evt);
            }
        });

        delnameJTF.setEditable(false);
        delnameJTF.setBackground(new java.awt.Color(224, 224, 224));
        delnameJTF.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        delnameJTF.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(118, 138, 168));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Delete Selected Enterprise Admin:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(enterpriseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enterpriseTypeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(backJButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel4)
                                                                .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(42, 42, 42)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel5)
                                                                .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(submitJButton)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(162, 162, 162)
                                            .addComponent(renameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(renameJB))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(77, 77, 77)
                                            .addComponent(delnameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(delJB)))))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {backJButton, delJB, renameJB, submitJButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enterpriseTypeJTF, nameJTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addComponent(jLabel3))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterpriseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterpriseTypeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(submitJButton)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(renameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(renameJB))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(delnameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delJB))
                        .addGap(149, 149, 149)
                        .addComponent(backJButton)))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backJButton, renameJB, submitJButton});

    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
        
        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String name = nameJTextField.getText();
        boolean x=false,y=false,z=false,x2=true,y2=true,z2=true;
        for(Network nw:system.getNetworkList()){
            
            for(Enterprise e:nw.getEnterpriseDirectory().getEnterpriseList()){
                    
                    x=system.getUserAccountDirectory().checkIfUsernameIsUnique(username);
                    y=e.getUserAccountDirectory().checkIfUsernameIsUnique(username);
                    z=nw.getUserAccountDirectory().checkIfUsernameIsUnique(username);
                    if(x==false) x2=x;
                    if(y==false) y2=y;
                    if(z==false) z2=z;
                
            }
        }
        
        if(x2==true && y2==true && z2==true){
            People people= enterprise.getPeopleDirectory().createPeople(name);

            if(enterpriseTypeJTF.getText().equals("Hospitals")){
                UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, people, new HAdminRole());
            }else if(enterpriseTypeJTF.getText().equals("PharmacySupplier")){
                UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, people, new PSAdminRole());
            }else if(enterpriseTypeJTF.getText().equals("MedicalInsurance")){
                UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, people, new MIAdminRole());
            }
            populateTable();
            JOptionPane.showMessageDialog(null,"Create successfully");
            usernameJTextField.setText("");
            passwordJPasswordField.setText("");
            nameJTextField.setText("");
        }else{
            JOptionPane.showMessageDialog(null,"Username already existed");
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
               
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:
        Enterprise e=(Enterprise)enterpriseJComboBox.getSelectedItem();
        if (e != null){
            populateEnterpriseType(e);
        }
        
    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed

    private void renameJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameJBActionPerformed
        // TODO add your handling code here:
        int selectedrow=enterpriseJTable.getSelectedRow();
        String newusername=renameJTF.getText();
        if(selectedrow>=0){
            UserAccount ua =(UserAccount)enterpriseJTable.getValueAt(selectedrow,0);
            for(Network nw:system.getNetworkList()){
                for(Enterprise e:nw.getEnterpriseDirectory().getEnterpriseList()){
                    for(UserAccount useraccount:e.getUserAccountDirectory().getUserAccountList()){
                        if(useraccount.equals(ua)){    
                            boolean x=system.getUserAccountDirectory().checkIfUsernameIsUnique(newusername);
                            boolean y=e.getUserAccountDirectory().checkIfUsernameIsUnique(newusername);
                            boolean z=nw.getUserAccountDirectory().checkIfUsernameIsUnique(newusername);
                            
                            if(x==true && y==true && z==true){
                                useraccount.setUsername(newusername);
                                JOptionPane.showMessageDialog(null,"Rename successfully");
                                renameJTF.setText("");
                                populateTable();
                            }else{
                                JOptionPane.showMessageDialog(null,"Username already existed");
                            }
                            
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_renameJBActionPerformed

    private void delJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delJBActionPerformed
        // TODO add your handling code here:
        int selectedrow=enterpriseJTable.getSelectedRow();
        if(selectedrow>=0){
            UserAccount ua =(UserAccount)enterpriseJTable.getValueAt(selectedrow,0);
            for(Network nw:system.getNetworkList()){
                for(Enterprise e:nw.getEnterpriseDirectory().getEnterpriseList()){
                    e.getUserAccountDirectory().deleteUserAccount(ua);
                    JOptionPane.showMessageDialog(null,"Delete successfully");
                    delnameJTF.setText("");
                    populateTable();
                    break;
                }
            }
        }
      
    }//GEN-LAST:event_delJBActionPerformed

    private void enterpriseJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterpriseJTableMouseClicked
        // TODO add your handling code here:
        int selectedrow=enterpriseJTable.getSelectedRow();
        if(selectedrow>=0){
            UserAccount ua =(UserAccount)enterpriseJTable.getValueAt(selectedrow,0);
            delnameJTF.setText(ua.getUsername());
        }
    }//GEN-LAST:event_enterpriseJTableMouseClicked

    private void enterpriseTypeJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseTypeJTFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton delJB;
    private javax.swing.JTextField delnameJTF;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JTextField enterpriseTypeJTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton renameJB;
    private javax.swing.JTextField renameJTF;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
