/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Abstract.User;
import Business.Users.Airliner;
import Business.Users.Customer;
import Business.Users.TravelAgency;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yizhe
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    private JButton btnSearch;
    private JButton btnManageFlights;
    private JButton btnManageAirliners;
    private JButton btnManageCustomers;
    private JButton btnLogout;
    private JButton btnLogin;
    private JLabel LabelLogin;
    private JPanel CardSequenceJPanel;
    private TravelAgency travelagency;
    private List<User> list;
    private JButton btnSearchAirliners;
    private JButton btnManageAirplanes;
    private JButton btnSearchFlights;
    private JButton btnManageTravelOffice;
    
    public LoginJPanel(TravelAgency travelagency,
            JPanel CardSequenceJPanel,JButton btnSearch,JButton btnManageFlights,JButton btnSearchAirliners,
            JButton btnManageCustomers,JButton btnLogout,JButton btnLogin,JLabel LabelLogin,JButton btnManageAirliners,
            JButton btnManageAirplanes,JButton btnSearchFlights,JButton btnManageTravelOffice) {
        initComponents();
        
        TFname.setVisible(false);
        this.travelagency=travelagency;
        this.CardSequenceJPanel=CardSequenceJPanel;
        this.btnSearch=btnSearch;
        this.btnManageCustomers=btnManageCustomers;
        this.btnManageFlights=btnManageFlights;
        this.btnManageAirliners=btnManageAirliners;
        this.btnLogout=btnLogout;
        this.btnLogin=btnLogin;
        this.LabelLogin=LabelLogin;
        this.btnManageAirliners=btnManageAirliners;
        this.btnManageAirplanes=btnManageAirplanes;
        this.btnSearchFlights=btnSearchFlights;
        this.btnManageTravelOffice=btnManageTravelOffice;
        this.btnSearchAirliners=btnSearchAirliners;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TFname = new javax.swing.JTextField();
        TFpswd = new javax.swing.JTextField();
        btn_Login = new javax.swing.JButton();
        TypeJCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btn_signup = new javax.swing.JButton();
        NameJCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnChoose = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 650));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("User Login");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Password:");

        TFname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TFname.setForeground(new java.awt.Color(0, 0, 0));

        TFpswd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TFpswd.setForeground(new java.awt.Color(0, 0, 0));

        btn_Login.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });

        TypeJCB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TypeJCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Airliner", "TravelAgency" }));
        TypeJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeJCBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("UserType:");

        btn_signup.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_signup.setText("Sign Up");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });

        NameJCB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NameJCB.setToolTipText("");
        NameJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameJCBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Username:");

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TypeJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(NameJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnChoose))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TFpswd, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TFpswd, TypeJCB});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(370, 370, 370))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnChoose)
                        .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NameJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Login)
                    .addComponent(btn_signup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        
        if(TFpswd.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"enter password");
            return;
        }
        
        if (TypeJCB.getSelectedIndex()==2){
            if(TFname.getText().equals("admin") && TFpswd.getText().equals("admin")){
                jumpInterface();
            }else{
                TFpswd.setBorder(BorderFactory.createLineBorder(Color.RED));
                JOptionPane.showMessageDialog(this,"enter valid password"+"ensure selected correct supplier");
            }
            return;
        }
      
        User u=(User)NameJCB.getSelectedItem();
        if(u!=null && TypeJCB.getSelectedIndex()==0){
            Customer c=(Customer)u;
            if(c.verify(TFpswd.getText())){
                jumpInterface();
            }else{
                TFpswd.setBorder(BorderFactory.createLineBorder(Color.RED));
                JOptionPane.showMessageDialog(this,"enter valid password"+"ensure selected correct supplier");
            }
        }
        else if (u!=null && TypeJCB.getSelectedIndex()==1){
            Airliner a=(Airliner)u;
            if(a.verify(TFpswd.getText())){
                jumpInterface();
            }else{
                TFpswd.setBorder(BorderFactory.createLineBorder(Color.RED));
                JOptionPane.showMessageDialog(this,"enter valid password"+"ensure selected correct supplier");
            }
        }
        
        
    }//GEN-LAST:event_btn_LoginActionPerformed
    public void jumpInterface(){
        
        if(TypeJCB.getSelectedIndex()==0){
            btnManageAirliners.setEnabled(false);
            btnSearchAirliners.setEnabled(false);
            btnManageCustomers.setEnabled(false);
            btnSearch.setEnabled(true);
            btnManageFlights.setEnabled(false);
            btnManageAirplanes.setEnabled(false);
            btnSearchFlights.setEnabled(false);
            btnManageTravelOffice.setEnabled(false);
            LabelLogin.setText(""+NameJCB.getSelectedItem());
        }else if(TypeJCB.getSelectedIndex()==1){
            btnManageFlights.setEnabled(true);
            btnSearchAirliners.setEnabled(false);
            btnManageAirplanes.setEnabled(true);
            btnSearch.setEnabled(false);
            btnManageAirliners.setEnabled(true);
            btnManageCustomers.setEnabled(false);
            btnSearchFlights.setEnabled(false);
            btnManageTravelOffice.setEnabled(false);
            LabelLogin.setText(""+NameJCB.getSelectedItem());
        }else if(TypeJCB.getSelectedIndex()==2){
            btnSearch.setEnabled(false);
            btnManageFlights.setEnabled(false);
            btnSearchAirliners.setEnabled(true);
            btnManageAirplanes.setEnabled(false);
            btnManageAirliners.setEnabled(false);
            btnManageCustomers.setEnabled(true);
            btnSearchFlights.setEnabled(true);
            btnManageTravelOffice.setEnabled(true);
            LabelLogin.setText("Travel Agency");
        }
        btnLogout.setEnabled(true);
        btnLogin.setEnabled(false);
        JOptionPane.showMessageDialog(null,"Login Successfully");
        LoginSuccessJPanel lsjp=new LoginSuccessJPanel(CardSequenceJPanel);
        CardSequenceJPanel.add(lsjp);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
        
    }
    
    
    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        if(TypeJCB.getSelectedIndex()==2){ 
            JOptionPane.showMessageDialog(null,"you can't register as a travel agency");
        }else{       
        RegisterJPanel rjp=new RegisterJPanel(travelagency,CardSequenceJPanel);
        CardSequenceJPanel.add(rjp);
        CardLayout ly=(CardLayout)CardSequenceJPanel.getLayout();
        ly.next(CardSequenceJPanel);
        }
         
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        
            TFname.setText(null);
            NameJCB.removeAllItems();

            if(TypeJCB.getSelectedIndex()==0){
                list=travelagency.getCustomerDir().getCustomerdirectory();
            }else if(TypeJCB.getSelectedIndex()==1){
                list=travelagency.getAirlinerDir().getAirlinerdirectory();
            }else if(TypeJCB.getSelectedIndex()==2){
                list=travelagency.getCustomerDir().getCustomerdirectory();
                NameJCB.addItem("admin");
            }
            
            if(list.isEmpty() && TypeJCB.getSelectedIndex()!=2){
                    JOptionPane.showMessageDialog(null,"null");
                    return;
                    }

            for(User u:list){
                if(TypeJCB.getSelectedItem().equals("TravelAgency"))
                    break;
                else{
                    NameJCB.addItem(u);
                }
            }
            
        
    }//GEN-LAST:event_btnChooseActionPerformed

    private void NameJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameJCBActionPerformed
        // TODO add your handling code here:
        try{
        TFname.setText(NameJCB.getSelectedItem().toString());
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_NameJCBActionPerformed

    private void TypeJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeJCBActionPerformed
        // TODO add your handling code here:
        TFname.setText(null);
        NameJCB.removeAllItems();
    }//GEN-LAST:event_TypeJCBActionPerformed
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> NameJCB;
    private javax.swing.JTextField TFname;
    private javax.swing.JTextField TFpswd;
    private javax.swing.JComboBox<String> TypeJCB;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
