/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlinerDirectory;
import Business.AirplaneFleet;
import Business.FlightSchedule;
import Business.TicketDirectory;
import Business.TravelofficeDirectory;
import Business.Users.TravelAgency;
import UserInterface.SearchAirliners.SearchAirlinersJPanel;
import UserInterface.ManageFlights.ManageAirlinerFlightScheduleJPanel;
import UserInterface.CustomerService.ManageMasterFlightScheduleJPanel;
import UserInterface.ManageAirliners.ManageAirlinersJPanel;
import UserInterface.ManageAirplanes.ManageAirplanesJPanel;
import UserInterface.ManageCustomers.ManageCustomersJPanel;
import UserInterface.ManageOffice.ManageofficeJPanel;
import UserInterface.SearchFlights.SearchFlightsJPanel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;


/**
 *
 * @author yizhe
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMain
     */

private TravelAgency travelagency;
private AirlinerDirectory airlinerdirectory;
private FlightSchedule flightschedule;
private TicketDirectory ticketdirectory;
private AirplaneFleet airplanefleet;
private TravelofficeDirectory tod;

    private TravelAgencyMain() {
        initComponents();
        travelagency =new TravelAgency();
        airlinerdirectory=new AirlinerDirectory();
        flightschedule=new FlightSchedule();
        ticketdirectory=new TicketDirectory();
        airplanefleet=new AirplaneFleet();
        tod=new TravelofficeDirectory();
        btnSearch.setEnabled(false);
        btnManageFlights.setEnabled(false);
        btnManageAirliners.setEnabled(false);
        btnManageCustomers.setEnabled(false);
        btnLogout.setEnabled(false);
        btnSearchAirliners.setEnabled(false);
        btnManageAirliners.setEnabled(false);
        btnSearchFlights.setEnabled(false);
        btnManageAirplanes.setEnabled(false);
        btnManageTravelOffice.setEnabled(false);
        time();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CardSequenceJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnManageFlights = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnManageAirliners = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnManageCustomers = new javax.swing.JButton();
        LabelLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        LabelTime = new javax.swing.JLabel();
        btnSearchAirliners = new javax.swing.JButton();
        btnSearchFlights = new javax.swing.JButton();
        btnManageAirplanes = new javax.swing.JButton();
        btnManageTravelOffice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 750));

        CardSequenceJPanel.setPreferredSize(new java.awt.Dimension(800, 700));
        CardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(CardSequenceJPanel);

        jPanel1.setMinimumSize(new java.awt.Dimension(250, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageFlights.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManageFlights.setText("Manage Flights");
        btnManageFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightsActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, -1));

        btnSearch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 200, -1));

        btnManageAirliners.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManageAirliners.setText("Manage Airliners");
        btnManageAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlinersActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 200, -1));

        btnLogout.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 100, -1));

        btnManageCustomers.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManageCustomers.setText("Manage Customers");
        btnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, -1));

        LabelLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelLogin.setText("Login Here!!!");
        jPanel1.add(LabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Travel Agency Permissions");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Airliners Permission");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 190, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 260, 20));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 260, 10));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Customers Permission");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 210, -1));

        btnLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Current Time:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, -1));

        LabelTime.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        LabelTime.setForeground(java.awt.Color.blue);
        LabelTime.setText("Time");
        jPanel1.add(LabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, -1));

        btnSearchAirliners.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSearchAirliners.setText("Search Airliners");
        btnSearchAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAirlinersActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, -1));

        btnSearchFlights.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSearchFlights.setText("Search Flights");
        btnSearchFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFlightsActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, -1));

        btnManageAirplanes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManageAirplanes.setText("Manage Airplanes");
        btnManageAirplanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirplanesActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageAirplanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 200, -1));

        btnManageTravelOffice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManageTravelOffice.setText("Manage T-Office");
        btnManageTravelOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTravelOfficeActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageTravelOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Hi!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void time(){
        TimerTask task = new TimerTask() {  
            @Override  
            public void run() {  
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                LabelTime.setText(df.format(new Date())); 
            }  
        };  
        Timer timer = new Timer();  
        long delay = 0;  
        long intevalPeriod = 1 * 1000;
        timer.scheduleAtFixedRate(task, delay, intevalPeriod);
        
    }
    
    
    private void btnManageFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightsActionPerformed
        // TODO add your handling code here:
        ManageAirlinerFlightScheduleJPanel mafsjp = new ManageAirlinerFlightScheduleJPanel(CardSequenceJPanel,flightschedule);
        CardSequenceJPanel.add(mafsjp); 
        ((java.awt.CardLayout)CardSequenceJPanel.getLayout()).next(CardSequenceJPanel);
    }//GEN-LAST:event_btnManageFlightsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        ManageMasterFlightScheduleJPanel mmfsjp=new ManageMasterFlightScheduleJPanel(CardSequenceJPanel,airlinerdirectory,flightschedule,ticketdirectory,LabelLogin.getText(),btnLogout);
        CardSequenceJPanel.add(mmfsjp);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnManageAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlinersActionPerformed
        // TODO add your handling code here:
        ManageAirlinersJPanel majp = new ManageAirlinersJPanel(CardSequenceJPanel,travelagency,LabelLogin.getText());
        CardSequenceJPanel.add(majp);
        CardLayout ly=(CardLayout)CardSequenceJPanel.getLayout();
        ly.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnManageAirlinersActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        btnManageAirliners.setEnabled(false);
        btnManageCustomers.setEnabled(false);
        btnSearch.setEnabled(false);
        btnManageFlights.setEnabled(false);
        btnManageAirplanes.setEnabled(false);
        btnLogin.setEnabled(true);
        btnLogout.setEnabled(false);
        btnSearchAirliners.setEnabled(false);
        btnSearchFlights.setEnabled(false);
        btnManageTravelOffice.setEnabled(false);
        JOptionPane.showMessageDialog(null,"Log Out Successfully");
        CardSequenceJPanel.removeAll();
        btnLogin.doClick();
        LabelLogin.setText("Login Here!!!");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
        // TODO add your handling code here:
        ManageCustomersJPanel mcjp= new ManageCustomersJPanel(CardSequenceJPanel,travelagency,ticketdirectory);
        CardSequenceJPanel.add(mcjp);
        CardLayout ly=(CardLayout)CardSequenceJPanel.getLayout();
        ly.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        LoginJPanel ljp =new LoginJPanel(travelagency,CardSequenceJPanel,btnSearch,btnManageFlights,
                btnSearchAirliners,btnManageCustomers,btnLogout,btnLogin,LabelLogin,btnManageAirliners,btnManageAirplanes,btnSearchFlights,btnManageTravelOffice);
        CardSequenceJPanel.add(ljp);
        CardLayout ly=(CardLayout)CardSequenceJPanel.getLayout();
        ly.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSearchAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAirlinersActionPerformed
        // TODO add your handling code here:
        SearchAirlinersJPanel sajp=new SearchAirlinersJPanel(CardSequenceJPanel,airlinerdirectory);
        CardSequenceJPanel.add(sajp);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnSearchAirlinersActionPerformed

    private void btnSearchFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFlightsActionPerformed
        // TODO add your handling code here:
        SearchFlightsJPanel sfjp=new SearchFlightsJPanel(CardSequenceJPanel,flightschedule);
        CardSequenceJPanel.add(sfjp);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnSearchFlightsActionPerformed

    private void btnManageAirplanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirplanesActionPerformed
        // TODO add your handling code here:
        ManageAirplanesJPanel majp =new ManageAirplanesJPanel(CardSequenceJPanel,airplanefleet);
        CardSequenceJPanel.add(majp);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnManageAirplanesActionPerformed

    private void btnManageTravelOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTravelOfficeActionPerformed
        // TODO add your handling code here:
        ManageofficeJPanel mo =new ManageofficeJPanel(CardSequenceJPanel,tod);
        CardSequenceJPanel.add(mo);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnManageTravelOfficeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequenceJPanel;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelTime;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAirliners;
    private javax.swing.JButton btnManageAirplanes;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnManageFlights;
    private javax.swing.JButton btnManageTravelOffice;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchAirliners;
    private javax.swing.JButton btnSearchFlights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
