/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.HIS;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author EZ
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private HIS system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    String userName;
    String password;
    JFrame jf;
    
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        Dimension screenSize =Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
//        System.out.print(screenSize);
        newSystemMap();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        StatusJmenu = new javax.swing.JMenu();
        VSJMI = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        HelpJmenu = new javax.swing.JMenu();
        teammemberJMI = new javax.swing.JMenuItem();
        helpJMI = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenu();
        exitJMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("    HIS (Hospital-related Information System)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1600, 800));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1400, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));

        jSplitPane1.setBackground(jPanel1.getBackground());
        jSplitPane1.setDividerSize(2);
        jSplitPane1.setForeground(jPanel1.getBackground());
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSplitPane1.setEnabled(false);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(2147483647, 800));
        jSplitPane1.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(238, 237, 235));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 120));
        jPanel1.setLayout(null);

        loginJButton.setBackground(new java.awt.Color(219, 221, 234));
        loginJButton.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        loginJButton.setForeground(new java.awt.Color(0, 0, 0));
        loginJButton.setText("Login");
        loginJButton.setToolTipText("");
        loginJButton.setOpaque(false);
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginJButton);
        loginJButton.setBounds(1700, 20, 168, 40);

        jLabel3.setBackground(new java.awt.Color(48, 99, 86));
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Hospital Information System");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 10, 599, 56);

        userNameJTextField.setBackground(new java.awt.Color(224, 224, 224));
        userNameJTextField.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        userNameJTextField.setForeground(new java.awt.Color(0, 0, 0));
        userNameJTextField.setCaretColor(new java.awt.Color(0, 0, 0));
        userNameJTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userNameJTextField.setOpaque(false);
        jPanel1.add(userNameJTextField);
        userNameJTextField.setBounds(1520, 20, 168, 30);

        passwordField.setBackground(new java.awt.Color(224, 224, 224));
        passwordField.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        passwordField.setForeground(new java.awt.Color(0, 0, 0));
        passwordField.setCaretColor(new java.awt.Color(0, 0, 0));
        passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordField.setOpaque(false);
        jPanel1.add(passwordField);
        passwordField.setBounds(1520, 70, 168, 30);

        jLabel1.setBackground(jPanel1.getBackground());
        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1410, 20, 100, 30);

        jLabel2.setBackground(jPanel1.getBackground());
        jLabel2.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1420, 70, 90, 30);
        jPanel1.add(loginJLabel);
        loginJLabel.setBounds(0, 0, 0, 0);

        logoutJButton.setBackground(new java.awt.Color(219, 221, 234));
        logoutJButton.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        logoutJButton.setForeground(new java.awt.Color(0, 0, 0));
        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.setOpaque(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutJButton);
        logoutJButton.setBounds(1700, 60, 168, 40);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setToolTipText("");
        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 80, 800, 16);

        jLabel4.setBackground(new java.awt.Color(48, 99, 86));
        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("JS Info");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(699, 13, 127, 40);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/top.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(1920, 120));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1920, 120);

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(jPanel1.getBackground());
        container.setPreferredSize(new java.awt.Dimension(1200, 800));
        container.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(217, 224, 232));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 600));
        jPanel2.setLayout(null);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MI.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jLabel6.setMaximumSize(new java.awt.Dimension(289, 277));
        jLabel6.setMinimumSize(new java.awt.Dimension(289, 277));
        jLabel6.setPreferredSize(new java.awt.Dimension(289, 277));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(400, 260, 250, 250);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/patient.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(1110, 480, 250, 250);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/supplier.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jLabel5.setMaximumSize(new java.awt.Dimension(289, 277));
        jLabel5.setMinimumSize(new java.awt.Dimension(289, 277));
        jLabel5.setPreferredSize(new java.awt.Dimension(289, 277));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(58, 114, 250, 250);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MGH.png"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(760, 400, 250, 250);

        jLabel9.setBackground(new java.awt.Color(48, 99, 86));
        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 3, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pharmacy Suppliers");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(58, 382, 244, 32);

        jLabel10.setBackground(new java.awt.Color(48, 99, 86));
        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 3, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Medical Insurance");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(400, 540, 244, 32);

        jLabel11.setBackground(new java.awt.Color(48, 99, 86));
        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 3, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Hospitals");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(760, 350, 244, 32);

        jLabel12.setBackground(new java.awt.Color(48, 99, 86));
        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 3, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Patients");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(1110, 430, 244, 32);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/center - Copy.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(0, 0, 1920, 940);

        container.add(jPanel2, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(214, 219, 233));
        jMenuBar1.setForeground(jPanel1.getBackground());
        jMenuBar1.setMaximumSize(new java.awt.Dimension(240, 800));

        StatusJmenu.setBackground(jPanel1.getBackground());
        StatusJmenu.setText("Status");
        StatusJmenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        StatusJmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusJmenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StatusJmenu.setPreferredSize(new java.awt.Dimension(80, 29));

        VSJMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        VSJMI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        VSJMI.setText("View Status");
        VSJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VSJMIActionPerformed(evt);
            }
        });
        StatusJmenu.add(VSJMI);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem1.setText("System Map");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        StatusJmenu.add(jMenuItem1);

        jMenuBar1.add(StatusJmenu);

        HelpJmenu.setBackground(jPanel1.getBackground());
        HelpJmenu.setText("Help");
        HelpJmenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        HelpJmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HelpJmenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HelpJmenu.setPreferredSize(new java.awt.Dimension(80, 29));

        teammemberJMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        teammemberJMI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        teammemberJMI.setText("Team Members");
        teammemberJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teammemberJMIActionPerformed(evt);
            }
        });
        HelpJmenu.add(teammemberJMI);

        helpJMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        helpJMI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        helpJMI.setText("Operation manual");
        helpJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpJMIActionPerformed(evt);
            }
        });
        HelpJmenu.add(helpJMI);

        jMenuBar1.add(HelpJmenu);

        Exit.setBackground(jPanel1.getBackground());
        Exit.setText("Exit");
        Exit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Exit.setPreferredSize(new java.awt.Dimension(80, 29));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        exitJMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.ALT_MASK));
        exitJMI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exitJMI.setText("Exit");
        exitJMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJMIActionPerformed(evt);
            }
        });
        Exit.add(exitJMI);

        jMenuBar1.add(Exit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name
        userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        password = String.valueOf(passwordCharArray);
        
        //Step1: Check in the system admin user account directory if you have the user
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
        
        Network inNetwork=null;
        Enterprise inEnterprise=null;
        Organization inOrganization=null;
        
        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                userAccount=network.getUserAccountDirectory().authenticateUser(userName, password);
                if(userAccount==null){
                //Step 2.a: check against each enterprise
                    for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                        userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if(userAccount==null){
                           //Step 3:check against each organization for each enterprise
                           for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                               userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                               if(userAccount!=null){
                                   inNetwork=network;
                                   inEnterprise=enterprise;
                                   inOrganization=organization;
                                   break;
                               }
                           }//0rg

                        }else{
                           inNetwork=network;
                           inEnterprise=enterprise;
                           break;
                        }
                        if(inOrganization!=null){
                            break;
                        }  
                    }//etp
                }else{
                    inNetwork=network;
                    break;
                }
                if(inEnterprise!=null){
                    break;
                }
            }//netw
        }
        
        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            CardLayout layout=(CardLayout)container.getLayout();
            container.add("workArea",userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, inNetwork,system));
            layout.next(container);
        }
        
        loginJButton.setEnabled(false);
        logoutJButton.setEnabled(true);
        userNameJTextField.setEnabled(false);
        passwordField.setEnabled(false);
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        blankJP.setBackground(jPanel1.getBackground());
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        dB4OUtil.storeSystem(system);
        if(jf!=null){
            jf.dispose();
        }
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void VSJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VSJMIActionPerformed
        
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password); 
        if(userName!=null && password!=null){
            jf=new JFrame();
            jf.setTitle(" Current Status ");
            Rectangle thisFrame = this.getBounds();
            jf.setBounds(thisFrame.x+1920-480,thisFrame.y+570, 480, 500);
            StatusJPanel sjp=new StatusJPanel(userName,password,jPanel1.getBackground());
            jf.add(sjp);
            jf.setVisible(true);
            jf.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_VSJMIActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ExitActionPerformed

    private void helpJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpJMIActionPerformed
        try {
            // TODO add your handling code here:
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI("http://www.baidu.com"));
            } catch (IOException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_helpJMIActionPerformed

    private void exitJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJMIActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitJMIActionPerformed

    private void teammemberJMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teammemberJMIActionPerformed
        // TODO add your handling code here:
        JFrame jf2=new JFrame();
        jf2.setTitle(" Team Info ");
        jf2.setBounds(660,360, 600, 300);
        TeamJPanel tjp =new TeamJPanel(jPanel1.getBackground());
        jf2.add(tjp);
        jf2.setVisible(true);
        jf2.setAlwaysOnTop(true);
    }//GEN-LAST:event_teammemberJMIActionPerformed

    public void newSystemMap(){
        JFrame jf3=new JFrame();
        jf3.setTitle(" System Map ");
        Rectangle thisFrame = this.getBounds();
        jf3.setBounds(thisFrame.x+1920-480,thisFrame.y+70+120, 480, 500);
        SystemMapJPanel tjp =new SystemMapJPanel(system,jPanel1.getBackground());
        jf3.add(tjp);
        jf3.setVisible(true);
        jf3.setAlwaysOnTop(true);
        
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        newSystemMap();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu HelpJmenu;
    private javax.swing.JMenu StatusJmenu;
    private javax.swing.JMenuItem VSJMI;
    private javax.swing.JPanel container;
    private javax.swing.JMenuItem exitJMI;
    private javax.swing.JMenuItem helpJMI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JMenuItem teammemberJMI;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
