/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Role.Role;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.Timer;
import java.util.TimerTask;


/**
 *
 * @author yizhe
 */
public class StatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatusJPanel
     */
    String username;
    String password;
    Color c;
    public StatusJPanel(String username,String password,Color c) {
        initComponents();
        this.username=username;
        this.password=password;
        this.c=c;
        nameJTF.setText(username);
        passwordJTF.setText(password);
        setBackground(c);
        nameJTF.setBackground(c);
        passwordJTF.setBackground(c);
        timer1();
        timer2();
    }
    
    public void timer1(){
        Timer nTimer = new Timer();
        nTimer.schedule(new TimerTask() {
            @Override
            public void run() {
                nameJTF.setForeground(Color.YELLOW);
                passwordJTF.setForeground(Color.YELLOW);
//                switch(role.toString()){
//                    case "Business.Role.PSAdminRole":PSA.setForeground(Color.YELLOW);
//                    case "Business.Role.SalesmanRole":SM.setForeground(Color.YELLOW);
//                    case "Business.Role.WarehousemanRole":WM.setForeground(Color.YELLOW);
//                    case "Business.Role.HAdminRole":HA.setForeground(Color.YELLOW);
//                    case "Business.Role.DoctorRole":D.setForeground(Color.YELLOW);
//                    case "Business.Role.AccountantRole":A.setForeground(Color.YELLOW);
//                    case "Business.Role.PharacistRole":P.setForeground(Color.YELLOW);
//                    case "Business.Role.MIAdminRole":MIA.setForeground(Color.YELLOW);
//                    case "Business.Role.MIpersonnelRole":MIP.setForeground(Color.YELLOW);
//                    case "Business.Role.PatientRole":Pt.setForeground(Color.YELLOW);
//                    case "Business.Role.SystemAdminRole":SA.setForeground(Color.YELLOW);
//                }
                
            }
        },0,200);
    }
    
    public void timer2(){
        Timer nTimer = new Timer();
        nTimer.schedule(new TimerTask() {
            @Override
            public void run() {
                nameJTF.setForeground(Color.WHITE);
                passwordJTF.setForeground(Color.WHITE);
//                switch(role.toString()){
//                    case "Business.Role.PSAdminRole":PSA.setForeground(Color.WHITE);
//                    case "Business.Role.SalesmanRole":SM.setForeground(Color.WHITE);
//                    case "Business.Role.WarehousemanRole":WM.setForeground(Color.WHITE);
//                    case "Business.Role.HAdminRole":HA.setForeground(Color.WHITE);
//                    case "Business.Role.DoctorRole":D.setForeground(Color.WHITE);
//                    case "Business.Role.AccountantRole":A.setForeground(Color.WHITE);
//                    case "Business.Role.PharacistRole":P.setForeground(Color.WHITE);
//                    case "Business.Role.MIAdminRole":MIA.setForeground(Color.WHITE);
//                    case "Business.Role.MIpersonnelRole":MIP.setForeground(Color.WHITE);
//                    case "Business.Role.PatientRole":Pt.setForeground(Color.WHITE);
//                    case "Business.Role.SystemAdminRole":SA.setForeground(Color.WHITE);
//                }
            }
        },0,200);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPM = new javax.swing.JPopupMenu();
        JMI1 = new javax.swing.JMenuItem();
        JMI2 = new javax.swing.JMenuItem();
        JMI3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameJTF = new javax.swing.JTextField();
        passwordJTF = new javax.swing.JTextField();

        JMI1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JMI1.setText("Refresh");
        JMI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI1ActionPerformed(evt);
            }
        });
        JPM.add(JMI1);

        JMI2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JMI2.setText("Controlling  Info");
        JPM.add(JMI2);

        JMI3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JMI3.setText("Thumbs-up");
        JPM.add(JMI3);

        setBackground(new java.awt.Color(228, 225, 220));
        setPreferredSize(new java.awt.Dimension(500, 800));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabel1.setBackground(JPM.getBackground());
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Status");

        jLabel2.setBackground(JPM.getBackground());
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("UserName:");

        jLabel3.setBackground(JPM.getBackground());
        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password:");

        nameJTF.setEditable(false);
        nameJTF.setBackground(new java.awt.Color(234, 234, 234));
        nameJTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nameJTF.setForeground(new java.awt.Color(0, 0, 0));
        nameJTF.setCaretColor(new java.awt.Color(0, 0, 0));
        nameJTF.setOpaque(false);
        nameJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTFActionPerformed(evt);
            }
        });

        passwordJTF.setEditable(false);
        passwordJTF.setBackground(new java.awt.Color(234, 234, 234));
        passwordJTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordJTF.setForeground(new java.awt.Color(0, 0, 0));
        passwordJTF.setCaretColor(new java.awt.Color(0, 0, 0));
        passwordJTF.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameJTF)
                    .addComponent(passwordJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(670, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        if(evt.getButton()== MouseEvent.BUTTON3){
            JPM.show(this,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_formMousePressed

    private void nameJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTFActionPerformed

    private void JMI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI1ActionPerformed

//    public void popTable(){
//        DefaultTableModel dtm=(DefaultTableModel)viewJTable.getModel();
//        dtm.setRowCount(0);
//        
//        List<String> x=new ArrayList<>();
//        x.add("System Admin");
//        x.add("PS Admin");
//        x.add("H Admin");
//        x.add("MI Admin");
//        x.add("Patients");
//        x.add("Saleman");
//        x.add("Warehouseman");
//        x.add("Doctor");
//        x.add("Accountant");
//        x.add("Pharmacist");
//        x.add("MIpersonnel");
//       
//        Object row1[]=new Object[3];
//        row1[0]=x.get(0);
//        row1[1]=x.get(1);
//        row1[2]=x.get(5);
//        dtm.addRow(row1);
//        
//        Object row2[]=new Object[3];
//        row2[2]=x.get(6);
//        dtm.addRow(row2);
//        
//        Object row3[]=new Object[3];
//        row3[1]=x.get(2);
//        row3[2]=x.get(7);
//        dtm.addRow(row3);
//        
//        Object row4[]=new Object[3];
//        row4[2]=x.get(8);
//        dtm.addRow(row4);
//        
//        Object row5[]=new Object[3];
//        row5[2]=x.get(9);
//        dtm.addRow(row5);
//        
//        Object row6[]=new Object[3];
//        row6[1]=x.get(3);
//        row6[2]=x.get(10);
//        dtm.addRow(row6);
//        
//        Object row7[]=new Object[3];
//        row7[1]=x.get(4);
//        dtm.addRow(row7);
//       
//            
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMI1;
    private javax.swing.JMenuItem JMI2;
    private javax.swing.JMenuItem JMI3;
    private javax.swing.JPopupMenu JPM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameJTF;
    private javax.swing.JTextField passwordJTF;
    // End of variables declaration//GEN-END:variables
}
