/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Abstract.User;
import Business.Ticket;
import Business.TicketDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yizhe
 */
public class CustomerBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerBookingJPanel
     */
    private JPanel CardSequenceJPanel;
    private String username;
    private TicketDirectory ticketdirectory;
    public CustomerBookingJPanel(JPanel CardSequenceJPanel,String username,TicketDirectory ticketdirectory) {
        initComponents();
        this.CardSequenceJPanel=CardSequenceJPanel;
        this.username=username;
        this.ticketdirectory=ticketdirectory;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketJTB = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ticketJTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TicketID", "Username", "FlightNo", "SeatNo", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ticketJTB);
        if (ticketJTB.getColumnModel().getColumnCount() > 0) {
            ticketJTB.getColumnModel().getColumn(0).setResizable(false);
            ticketJTB.getColumnModel().getColumn(1).setResizable(false);
            ticketJTB.getColumnModel().getColumn(2).setResizable(false);
            ticketJTB.getColumnModel().getColumn(3).setResizable(false);
            ticketJTB.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Cancel Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(366, 366, 366)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout=(CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        int selectedRow=ticketJTB.getSelectedRow();
        Ticket t=(Ticket)ticketJTB.getValueAt(selectedRow,0);
        ticketdirectory.cancelTicket(t);
        JOptionPane.showMessageDialog(null,"succeed!");
        populate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"select row");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populate(){
        DefaultTableModel dtm=(DefaultTableModel)ticketJTB.getModel();
        dtm.setRowCount(0);
        
        for(Ticket t:ticketdirectory.getTicketdirectory()){
        Object[] row=new Object[5];
        row[0]=t;
        row[1]=t.getUsername();
        row[2]=t.getFlightNo();
        row[3]=t.getSeatNo();
        row[4]=t.getPrice();
        
        dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ticketJTB;
    // End of variables declaration//GEN-END:variables
}
