/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;

/**
 *
 * @author yizhe
 */
public class LoginAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginAdminJPanel
     */
    String command;
    String command2;
    JPanel workJPanel;
    public LoginAdminJPanel(JPanel workJPanel) {
        initComponents();
        this.workJPanel=workJPanel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cmdJTA = new javax.swing.JTextArea();

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        cmdJTA.setBackground(new java.awt.Color(19, 21, 34));
        cmdJTA.setColumns(20);
        cmdJTA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cmdJTA.setForeground(new java.awt.Color(255, 255, 255));
        cmdJTA.setRows(5);
        cmdJTA.setText(">>");
        cmdJTA.setToolTipText("");
        cmdJTA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(204, 204, 204)), "  (c) 2019 JP Info Corporation. All rights reserved. ( Press 'ctrl' To execute )", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255)), "  JP INFO [Version 0.3.14159.265]\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 255, 255)), " Command", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        cmdJTA.setCaretColor(new java.awt.Color(255, 255, 255));
        cmdJTA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cmdJTA.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cmdJTA.setName(""); // NOI18N
        cmdJTA.setOpaque(false);
        cmdJTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdJTAKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(cmdJTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdJTAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdJTAKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_CONTROL){
            command=cmdJTA.getText().substring(2);

            if(command.equals("BOSS")){
                cmdJTA.setText(cmdJTA.getText()+'\n'+">>");
            }
            int start=cmdJTA.getText().indexOf(">",2);
            String newstring =cmdJTA.getText().replaceAll("\\s*", "") ;
            command2=newstring.substring(start+1);
            
            if(command2.equals("BOSS")){
                
                AdminJPanel ajp=new AdminJPanel(); 
                workJPanel.add(ajp);
                CardLayout lay=(CardLayout)workJPanel.getLayout();
                lay.next(workJPanel);
            }

        };
    }//GEN-LAST:event_cmdJTAKeyPressed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        cmdJTA.requestFocus();
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cmdJTA;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
