/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AccountantWorkArea;

import Business.Enterprise.Enterprise;
import Business.HIS;
import Business.Medicine.Medicine;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedPurchaseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ViewStorageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewStorageJPanel
     */
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount account;
    HIS system;
    Network network;
    Organization org;
    
    public ViewStorageJPanel(JPanel userProcessContainer, Enterprise enterprise,UserAccount account,HIS system,Network network,Organization org) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        
        this.account=account;
        this.system=system;
        this.network=network;
        this.org=org;
        populateTable();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        PTMedicine = new javax.swing.JComboBox();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StorageJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(224, 224, 224));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Medicine Name");

        PTMedicine.setBackground(new java.awt.Color(224, 224, 224));
        PTMedicine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PTMedicine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Antibiotics", "albomycin", "berberine", "penicillin G", "Analgesics", "aspirin", "Vitamins" }));
        PTMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTMedicineActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(224, 224, 224));
        btnSearch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(224, 224, 224));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(118, 138, 168));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Hospital Information System - Accountant WorkArea ");

        StorageJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "MedicineName", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(StorageJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(PTMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack)))
                .addContainerGap(1224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PTMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnBack)
                .addContainerGap(352, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        SearchMedicine();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void PTMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTMedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PTMedicineActionPerformed

    
    public void populateTable(){
        DefaultTableModel dtm=(DefaultTableModel)StorageJTable.getModel();
       dtm.setRowCount(0);
       HashMap<String,Integer> map1=enterprise.getStorageDir().getStorageDirectory();
       for(Map.Entry<String,Integer> entry:map1.entrySet()){
               Object[] row = new Object[2];
                row[0] = entry.getKey();
                row[1] = entry.getValue();
                dtm.addRow(row);
       }
    }
//    public void populateTable(){
//             
//        DefaultTableModel dtm = (DefaultTableModel) StorageJTable.getModel();
//        dtm.setRowCount(0);
//    
//         for(WorkRequest rq: account.getWorkQueue().getWorkRequestList()){
//                    
//              MedPurchaseWorkRequest mrq=(MedPurchaseWorkRequest)rq;
//                Medicine m=mrq.getMedicine();
//              if(m.getStatus()!="Pending"){
//               
//                Object[] row = new Object[2];
//                row[0] = m;
//                row[1] = m.getQuantity();
//                
//               dtm.addRow(row);
//          
//              }
//    }
//    }
    
     public void  SearchMedicine(){
       DefaultTableModel dtm=(DefaultTableModel)StorageJTable.getModel();
       dtm.setRowCount(0);
       String medicine=String.valueOf(PTMedicine.getSelectedItem());
       HashMap<String,Integer> map1=enterprise.getStorageDir().getStorageDirectory();
       for(Map.Entry<String,Integer> entry:map1.entrySet()){
           if(entry.getKey().equals(medicine)){
               Object[] row = new Object[2];
                row[0] = entry.getKey();
                row[1] = entry.getValue();
                dtm.addRow(row);
           }
       }
     
       
     }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PTMedicine;
    private javax.swing.JTable StorageJTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
