/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PSAdminWorkArea;

import Business.Enterprise.Enterprise;
import Business.HIS;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author yizhe
 */
public class PSAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PSAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    HIS ecosystem;
    Enterprise enterprise;
     
  

    public PSAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnManagePer = new javax.swing.JButton();
        btnMangeUser = new javax.swing.JButton();
        btnManageOrg = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(224, 224, 224));
        setLayout(null);

        jLabel2.setBackground(new java.awt.Color(224, 224, 224));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Hospital Information System - Pharmacy Supplier Admin ");
        add(jLabel2);
        jLabel2.setBounds(50, 50, 665, 34);

        btnManagePer.setBackground(new java.awt.Color(224, 224, 224));
        btnManagePer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManagePer.setText("Manage Related Personnel");
        btnManagePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePerActionPerformed(evt);
            }
        });
        add(btnManagePer);
        btnManagePer.setBounds(110, 170, 299, 35);

        btnMangeUser.setBackground(new java.awt.Color(224, 224, 224));
        btnMangeUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMangeUser.setText("Manage Related User");
        btnMangeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMangeUserActionPerformed(evt);
            }
        });
        add(btnMangeUser);
        btnMangeUser.setBounds(110, 230, 299, 35);

        btnManageOrg.setBackground(new java.awt.Color(224, 224, 224));
        btnManageOrg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnManageOrg.setText("Manage Organization");
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });
        add(btnManageOrg);
        btnManageOrg.setBounds(110, 110, 299, 35);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/center - Copy.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setPreferredSize(new java.awt.Dimension(1920, 1080));
        add(jLabel14);
        jLabel14.setBounds(0, 0, 1920, 960);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePerActionPerformed
        // TODO add your handling code here:
       PSManagePerJPanel psmp=new PSManagePerJPanel(userProcessContainer,enterprise);
        userProcessContainer.add(psmp);
        CardLayout ly=(CardLayout)userProcessContainer.getLayout();
        ly.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePerActionPerformed

    private void btnMangeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMangeUserActionPerformed
        // TODO add your handling code here:
        PSManageUserJPanel psmu=new PSManageUserJPanel(userProcessContainer,enterprise);
        userProcessContainer.add(psmu);
        CardLayout ly=(CardLayout)userProcessContainer.getLayout();
        ly.next(userProcessContainer);
    }//GEN-LAST:event_btnMangeUserActionPerformed

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        // TODO add your handling code here:
        PSManageOrgJPanel psmo=new PSManageOrgJPanel(userProcessContainer,enterprise);
        userProcessContainer.add(psmo);
        CardLayout ly=(CardLayout)userProcessContainer.getLayout();
        ly.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnManagePer;
    private javax.swing.JButton btnMangeUser;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
