/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PSAdminWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class PSManageOrgJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PSManageOrgJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    
    public PSManageOrgJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        populateTable();
        populateComBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PSOrgJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JcbEnterprise = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        JcbOrgType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRename = new javax.swing.JTextField();
        btnRename = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDeleteName = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(224, 224, 224));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setRequestFocusEnabled(false);

        jLabel8.setBackground(new java.awt.Color(224, 224, 224));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Hospital Information System - Pharmacy Supplier Organization");

        jScrollPane1.setBackground(new java.awt.Color(224, 224, 224));

        PSOrgJTable.setBackground(new java.awt.Color(224, 224, 224));
        PSOrgJTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PSOrgJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Org Name", "Org Type", "Enterprise"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PSOrgJTable.setGridColor(new java.awt.Color(0, 0, 0));
        PSOrgJTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        PSOrgJTable.setSelectionForeground(new java.awt.Color(255, 255, 0));
        PSOrgJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PSOrgJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PSOrgJTable);

        jLabel4.setBackground(new java.awt.Color(224, 224, 224));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Create New Organization:");

        jLabel1.setBackground(new java.awt.Color(224, 224, 224));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Enterprise");

        JcbEnterprise.setBackground(new java.awt.Color(224, 224, 224));
        JcbEnterprise.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JcbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JcbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbEnterpriseActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(224, 224, 224));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Organization Type");

        JcbOrgType.setBackground(new java.awt.Color(224, 224, 224));
        JcbOrgType.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JcbOrgType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setBackground(new java.awt.Color(224, 224, 224));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        txtName.setBackground(new java.awt.Color(224, 224, 224));
        txtName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));

        btnCreate.setBackground(new java.awt.Color(224, 224, 224));
        btnCreate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCreate.setText("Submit");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(224, 224, 224));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Rename Selected Organization:");

        jLabel7.setBackground(new java.awt.Color(224, 224, 224));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("ReName");

        txtRename.setBackground(new java.awt.Color(224, 224, 224));
        txtRename.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtRename.setCaretColor(new java.awt.Color(255, 255, 255));
        txtRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRenameActionPerformed(evt);
            }
        });

        btnRename.setBackground(new java.awt.Color(224, 224, 224));
        btnRename.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRename.setText("Submit");
        btnRename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenameActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(224, 224, 224));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Delete Selected Organization:");

        jLabel9.setBackground(new java.awt.Color(224, 224, 224));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Name");

        txtDeleteName.setEditable(false);
        txtDeleteName.setBackground(new java.awt.Color(224, 224, 224));
        txtDeleteName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtDeleteName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDeleteName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteNameActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(224, 224, 224));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(224, 224, 224));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(218, 218, 218)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCreate))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBack)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDeleteName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(132, 132, 132)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(JcbOrgType, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(JcbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtRename, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnRename, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(686, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JcbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JcbOrgType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCreate)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnRename)
                            .addComponent(txtRename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(jLabel9)
                            .addComponent(txtDeleteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btnBack)))
                .addContainerGap(520, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) PSOrgJTable.getModel();

        model.setRowCount(0);
        
            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                Object[] row = new Object[3];
                row[0] = org;
                row[1] = org.getOrganizationType().getValue();
                row[2] = enterprise.getName();

                model.addRow(row);
            }
        
    }
    public void populateComBox(){
        JcbEnterprise.removeAllItems();
        JcbEnterprise.addItem(enterprise);
        JcbOrgType.removeAllItems();
        for (Organization.OrganizationType type : Organization.OrganizationType.values()) {
            if(type.getValue().equals("SalesDept") ||type.getValue().equals("Warehouse") )
                JcbOrgType.addItem(type);
        }
    }
    
    private void PSOrgJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PSOrgJTableMouseClicked
       int selectedrow=PSOrgJTable.getSelectedRow();
        if(selectedrow >=0){
            Organization org=(Organization)PSOrgJTable.getValueAt(selectedrow,0);
            txtDeleteName.setText(org.getName());
        }
    }//GEN-LAST:event_PSOrgJTableMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        Enterprise enterprise = (Enterprise) JcbEnterprise.getSelectedItem();
        Organization.OrganizationType type = (Organization.OrganizationType) JcbOrgType.getSelectedItem();

        if (enterprise == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = txtName.getText();
        Organization org=enterprise.getOrganizationDirectory().createOrganization(type,name);
        
        populateTable();
        JOptionPane.showMessageDialog(null,"Create successfully");
   
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenameActionPerformed
        // TODO add your handling code here:
        int selectedrow=PSOrgJTable.getSelectedRow();
        if(selectedrow >=0){
            Organization org=(Organization)PSOrgJTable.getValueAt(selectedrow,0);
            org.setName(txtRename.getText());
            JOptionPane.showMessageDialog(null,"Rename successfully");
            populateTable();
        }
     
    }//GEN-LAST:event_btnRenameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
     int selectedrow=PSOrgJTable.getSelectedRow();
        int flag=0;
        if(selectedrow >=0){
            Organization org=(Organization)PSOrgJTable.getValueAt(selectedrow,0);
            for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                if(organization.equals(org)){
                    flag=1;
                }
            }
            if(flag==1){
                enterprise.getOrganizationDirectory().deleteOrganization(org);
                JOptionPane.showMessageDialog(null,"Delete successfully");
                populateTable();
            }
        }
       

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtDeleteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteNameActionPerformed

    private void JcbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbEnterpriseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtRenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRenameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JcbEnterprise;
    private javax.swing.JComboBox JcbOrgType;
    private javax.swing.JTable PSOrgJTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDeleteName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRename;
    // End of variables declaration//GEN-END:variables
}
