/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageFlights;

import Business.Flight;
import Business.FlightSchedule;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yizhe
 */
public class ManageAirlinerFlightScheduleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinerFlightScheduleJPanel
     */
    private JPanel CardSequenceJPanel;
    private FlightSchedule flightschedule;
    
    
    public ManageAirlinerFlightScheduleJPanel(JPanel CardSequenceJPanel,FlightSchedule flightschedule) {
        initComponents();
        this.CardSequenceJPanel=CardSequenceJPanel;     
        this.flightschedule=flightschedule;
        CardSequenceJPanel.removeAll();
        populateTable();
    }

     public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblflight.getModel();
        dtm.setRowCount(0);
        for(Flight flight: flightschedule.getFlightschedule()){
            Object[] row = new Object[6];
            row[0] = flight;
            row[1] = flight.getFlightNum();
            row[2] = flight.getAirplaneNum();
            row[3] = flight.getDepartLoc();
            row[4] = flight.getArrivalLoc();
            row[5] = flight.getTripType();
            
            dtm.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblflight = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Flight Schedule");

        btnCreate.setText("New Flight >>");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View Flights >>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        tblflight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Flight Number", "Airplane Number", "Depart Loction", "Arrival Location", "Trip Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblflight);
        if (tblflight.getColumnModel().getColumnCount() > 0) {
            tblflight.getColumnModel().getColumn(0).setResizable(false);
            tblflight.getColumnModel().getColumn(1).setResizable(false);
            tblflight.getColumnModel().getColumn(2).setResizable(false);
            tblflight.getColumnModel().getColumn(3).setResizable(false);
            tblflight.getColumnModel().getColumn(4).setResizable(false);
            tblflight.getColumnModel().getColumn(5).setResizable(false);
        }

        btnCancel.setText("Cancel Flights >>");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnCreate)
                .addGap(33, 33, 33)
                .addComponent(btnView)
                .addGap(32, 32, 32)
                .addComponent(btnCancel)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateNewFlightsJPanel cnfjp=new CreateNewFlightsJPanel(CardSequenceJPanel,flightschedule);
        CardSequenceJPanel.add(cnfjp);
        CardLayout layout= (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here: 
         int selectedRow = tblflight.getSelectedRow();
         if(selectedRow<0){
             JOptionPane.showMessageDialog(null,"Please select a row from table to view details","Warning",JOptionPane.WARNING_MESSAGE);
         }
         else{
             Flight flight = (Flight)tblflight.getValueAt(selectedRow,0);
                ViewFlightsJPanel vfjp=new ViewFlightsJPanel(CardSequenceJPanel,flight);
                CardSequenceJPanel.add("ViewFlightsJPanel",vfjp);
                CardLayout layout= (CardLayout)CardSequenceJPanel.getLayout();
               layout.next(CardSequenceJPanel);
         }        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblflight.getSelectedRow();
        if(selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to cancel the flight","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Flight flight = (Flight) tblflight.getValueAt(selectedRow, 0);
                flightschedule.cancelFlight(flight);
                populateTable();
        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row from the table","Warning",JOptionPane.WARNING_MESSAGE);
        }
     
    }                     
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblflight;
    // End of variables declaration//GEN-END:variables
}
